Import('RTT_ROOT')
Import('rtconfig')
from building import *

src  = Glob('*.c')
src += Glob('resource/*.c')
cwd  = GetCurrentDir()
LOCAL_CPPPATH = [cwd]

group = DefineGroup('ScreenProtect', src, depend = ['OLPC_APP_SRCSAVER_ENABLE'], LOCAL_CPPPATH = LOCAL_CPPPATH)

Return('group')
