# Import('RTT_ROOT')
# Import('rtconfig')
from building import *

src  = Glob('*.c')
src += Glob('resource/*.c')
cwd  = GetCurrentDir()
LOCAL_CPPPATH = [cwd]

group = DefineGroup('Clock', src, depend = ['OLPC_APP_CLOCK_ENABLE'], LOCAL_CPPPATH = LOCAL_CPPPATH)

Return('group')
