# Import('RTT_ROOT')
# Import('rtconfig')
from building import *

src  = Glob('*.c')
cwd  = GetCurrentDir()
LOCAL_CPPPATH = [cwd]

group = DefineGroup('olpc_common', src, depend = ['RT_USING_OLPC_DEMO'], LOCAL_CPPPATH = LOCAL_CPPPATH)

Return('group')
