# for olpc_demo apps compiling
import os
import rtconfig
from building import *

cwd = GetCurrentDir()
objs = []

if GetDepend(['RT_USING_OLPC_DEMO']):
    objs += SConscript(os.path.join('common', 'SConscript'))
    objs += SConscript(os.path.join('scrprotect', 'SConscript'))

    if not GetDepend(['OLPC_DLMODULE_ENABLE']):
        objs += SConscript(os.path.join('olpc_demo', 'SConscript'))

Return('objs')
